"""Added account table

Revision ID: b4c41f18a1da
Revises: 24fcd23d72f6
Create Date: 2022-06-17 23:04:25.352689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c41f18a1da'
down_revision = '24fcd23d72f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('contactType', sa.Enum('Email', 'Mobile', name='contacttype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_id'), 'car', ['id'], unique=False)
    op.create_index(op.f('ix_car_name'), 'car', ['name'], unique=False)
    op.create_index(op.f('ix_car_value'), 'car', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_value'), table_name='car')
    op.drop_index(op.f('ix_car_name'), table_name='car')
    op.drop_index(op.f('ix_car_id'), table_name='car')
    op.drop_table('car')
    # ### end Alembic commands ###
